//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 08:39:46 PM PDT 
//


package userProfile;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for listItemDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listItemDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entryUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listItemDef", namespace = "urn:oma:xml:xdm:user-profile", propOrder = {
    "entryUri"
})
public class ListItemDef {

    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String entryUri;

    /**
     * Gets the value of the entryUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryUri() {
        return entryUri;
    }

    /**
     * Sets the value of the entryUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryUri(String value) {
        this.entryUri = value;
    }

}
