//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 08:39:46 PM PDT 
//


package userProfile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keyList" type="{urn:oma:xml:xdm:user-profile}listDef"/>
 *         &lt;element name="user-profile" type="{urn:oma:xml:xdm:user-profile}user-profileType"/>
 *         &lt;element name="hgParticipationList" type="{urn:oma:xml:xdm:user-profile}hgListDef" minOccurs="0"/>
 *         &lt;element name="permissionedBusinessLinesList" type="{urn:oma:xml:xdm:user-profile}listDef" minOccurs="0"/>
 *         &lt;element name="permissionedConfLinesList" type="{urn:oma:xml:xdm:user-profile}listDef" minOccurs="0"/>
 *         &lt;element name="permissionedFaxLinesList" type="{urn:oma:xml:xdm:user-profile}listDef" minOccurs="0"/>
 *         &lt;element name="lineInfo" type="{urn:oma:xml:xdm:user-profile}LineInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dialout-permission" type="{urn:oma:xml:xdm:user-profile}dial-permission-type" minOccurs="0"/>
 *         &lt;element name="entid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="banid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailaddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ha1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ha2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ftn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="roles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oma:xml:xdm:user-profile}role"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="administeredBans" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oma:xml:xdm:user-profile}banid" maxOccurs="20"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="administeredGroups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oma:xml:xdm:user-profile}groupid" maxOccurs="30"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keyList",
    "userProfile",
    "hgParticipationList",
    "permissionedBusinessLinesList",
    "permissionedConfLinesList",
    "permissionedFaxLinesList",
    "lineInfo",
    "dialoutPermission",
    "entid",
    "domain",
    "banid",
    "emailaddress",
    "ha1",
    "ha2",
    "ftn",
    "roles",
    "administeredBans",
    "administeredGroups"
})
@XmlRootElement(name = "user-profiles", namespace = "urn:oma:xml:xdm:user-profile")
public class UserProfiles {

    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile", required = true)
    protected ListDef keyList;
    @XmlElement(name = "user-profile", namespace = "urn:oma:xml:xdm:user-profile", required = true)
    protected UserProfileType userProfile;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected HgListDef hgParticipationList;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected ListDef permissionedBusinessLinesList;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected ListDef permissionedConfLinesList;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected ListDef permissionedFaxLinesList;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected List<LineInfo> lineInfo;
    @XmlElement(name = "dialout-permission", namespace = "urn:oma:xml:xdm:user-profile", defaultValue = "allow-domestic")
    @XmlSchemaType(name = "string")
    protected DialPermissionType dialoutPermission;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String entid;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String domain;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String banid;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String emailaddress;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String ha1;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String ha2;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected String ftn;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected UserProfiles.Roles roles;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected UserProfiles.AdministeredBans administeredBans;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected UserProfiles.AdministeredGroups administeredGroups;

    /**
     * Gets the value of the keyList property.
     *
     * @return
     *     possible object is
     *     {@link ListDef }
     *
     */
    public ListDef getKeyList() {
        return keyList;
    }

    /**
     * Sets the value of the keyList property.
     *
     * @param value
     *     allowed object is
     *     {@link ListDef }
     *
     */
    public void setKeyList(ListDef value) {
        this.keyList = value;
    }

    /**
     * Gets the value of the userProfile property.
     *
     * @return
     *     possible object is
     *     {@link UserProfileType }
     *
     */
    public UserProfileType getUserProfile() {
        return userProfile;
    }

    /**
     * Sets the value of the userProfile property.
     *
     * @param value
     *     allowed object is
     *     {@link UserProfileType }
     *
     */
    public void setUserProfile(UserProfileType value) {
        this.userProfile = value;
    }

    /**
     * Gets the value of the hgParticipationList property.
     *
     * @return
     *     possible object is
     *     {@link HgListDef }
     *
     */
    public HgListDef getHgParticipationList() {
        return hgParticipationList;
    }

    /**
     * Sets the value of the hgParticipationList property.
     *
     * @param value
     *     allowed object is
     *     {@link HgListDef }
     *
     */
    public void setHgParticipationList(HgListDef value) {
        this.hgParticipationList = value;
    }

    /**
     * Gets the value of the permissionedBusinessLinesList property.
     *
     * @return
     *     possible object is
     *     {@link ListDef }
     *
     */
    public ListDef getPermissionedBusinessLinesList() {
        return permissionedBusinessLinesList;
    }

    /**
     * Sets the value of the permissionedBusinessLinesList property.
     *
     * @param value
     *     allowed object is
     *     {@link ListDef }
     *
     */
    public void setPermissionedBusinessLinesList(ListDef value) {
        this.permissionedBusinessLinesList = value;
    }

    /**
     * Gets the value of the permissionedConfLinesList property.
     *
     * @return
     *     possible object is
     *     {@link ListDef }
     *
     */
    public ListDef getPermissionedConfLinesList() {
        return permissionedConfLinesList;
    }

    /**
     * Sets the value of the permissionedConfLinesList property.
     *
     * @param value
     *     allowed object is
     *     {@link ListDef }
     *
     */
    public void setPermissionedConfLinesList(ListDef value) {
        this.permissionedConfLinesList = value;
    }

    /**
     * Gets the value of the permissionedFaxLinesList property.
     *
     * @return
     *     possible object is
     *     {@link ListDef }
     *
     */
    public ListDef getPermissionedFaxLinesList() {
        return permissionedFaxLinesList;
    }

    /**
     * Sets the value of the permissionedFaxLinesList property.
     *
     * @param value
     *     allowed object is
     *     {@link ListDef }
     *
     */
    public void setPermissionedFaxLinesList(ListDef value) {
        this.permissionedFaxLinesList = value;
    }

    /**
     * Gets the value of the lineInfo property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineInfo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineInfo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineInfo }
     *
     *
     */
    public List<LineInfo> getLineInfo() {
        if (lineInfo == null) {
            lineInfo = new ArrayList<LineInfo>();
        }
        return this.lineInfo;
    }

    /**
     * Gets the value of the dialoutPermission property.
     *
     * @return
     *     possible object is
     *     {@link DialPermissionType }
     *
     */
    public DialPermissionType getDialoutPermission() {
        return dialoutPermission;
    }

    /**
     * Sets the value of the dialoutPermission property.
     *
     * @param value
     *     allowed object is
     *     {@link DialPermissionType }
     *
     */
    public void setDialoutPermission(DialPermissionType value) {
        this.dialoutPermission = value;
    }

    /**
     * Gets the value of the entid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEntid() {
        return entid;
    }

    /**
     * Sets the value of the entid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEntid(String value) {
        this.entid = value;
    }

    /**
     * Gets the value of the domain property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the banid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBanid() {
        return banid;
    }

    /**
     * Sets the value of the banid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBanid(String value) {
        this.banid = value;
    }

    /**
     * Gets the value of the emailaddress property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * Sets the value of the emailaddress property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmailaddress(String value) {
        this.emailaddress = value;
    }

    /**
     * Gets the value of the ha1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHa1() {
        return ha1;
    }

    /**
     * Sets the value of the ha1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHa1(String value) {
        this.ha1 = value;
    }

    /**
     * Gets the value of the ha2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHa2() {
        return ha2;
    }

    /**
     * Sets the value of the ha2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHa2(String value) {
        this.ha2 = value;
    }

    /**
     * Gets the value of the ftn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFtn() {
        return ftn;
    }

    /**
     * Sets the value of the ftn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFtn(String value) {
        this.ftn = value;
    }

    /**
     * Gets the value of the roles property.
     *
     * @return
     *     possible object is
     *     {@link UserProfiles.Roles }
     *
     */
    public UserProfiles.Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     *
     * @param value
     *     allowed object is
     *     {@link UserProfiles.Roles }
     *
     */
    public void setRoles(UserProfiles.Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the administeredBans property.
     *
     * @return
     *     possible object is
     *     {@link UserProfiles.AdministeredBans }
     *
     */
    public UserProfiles.AdministeredBans getAdministeredBans() {
        return administeredBans;
    }

    /**
     * Sets the value of the administeredBans property.
     *
     * @param value
     *     allowed object is
     *     {@link UserProfiles.AdministeredBans }
     *
     */
    public void setAdministeredBans(UserProfiles.AdministeredBans value) {
        this.administeredBans = value;
    }

    /**
     * Gets the value of the administeredGroups property.
     *
     * @return
     *     possible object is
     *     {@link UserProfiles.AdministeredGroups }
     *
     */
    public UserProfiles.AdministeredGroups getAdministeredGroups() {
        return administeredGroups;
    }

    /**
     * Sets the value of the administeredGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link UserProfiles.AdministeredGroups }
     *
     */
    public void setAdministeredGroups(UserProfiles.AdministeredGroups value) {
        this.administeredGroups = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oma:xml:xdm:user-profile}banid" maxOccurs="20"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "banid"
    })
    public static class AdministeredBans {

        @XmlElement(namespace = "urn:oma:xml:xdm:user-profile", required = true)
        protected List<String> banid;

        /**
         * Gets the value of the banid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the banid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBanid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBanid() {
            if (banid == null) {
                banid = new ArrayList<String>();
            }
            return this.banid;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oma:xml:xdm:user-profile}groupid" maxOccurs="30"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupid"
    })
    public static class AdministeredGroups {

        @XmlElement(namespace = "urn:oma:xml:xdm:user-profile", required = true)
        protected List<String> groupid;

        /**
         * Gets the value of the groupid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroupid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGroupid() {
            if (groupid == null) {
                groupid = new ArrayList<String>();
            }
            return this.groupid;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oma:xml:xdm:user-profile}role"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role"
    })
    public static class Roles {

        @XmlElement(namespace = "urn:oma:xml:xdm:user-profile", required = true)
        protected String role;

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

    }

}
