//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 08:39:46 PM PDT 
//


package userProfile;

import org.w3c.dom.Element;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * <p>Java class for user-profileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user-profileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="communication-addresses" type="{urn:oma:xml:xdm:user-profile}communication-addressesType" minOccurs="0"/>
 *         &lt;element name="display-name" type="{urn:oma:xml:xdm:user-profile}display-nameType" minOccurs="0"/>
 *         &lt;element name="birth-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="name" type="{urn:oma:xml:xdm:user-profile}nameType" minOccurs="0"/>
 *         &lt;element name="address" type="{urn:oma:xml:xdm:user-profile}addressType" minOccurs="0"/>
 *         &lt;element name="gender" type="{urn:oma:xml:xdm:user-profile}genderType" minOccurs="0"/>
 *         &lt;element name="freetext" type="{urn:oma:xml:xdm:user-profile}freetextType" minOccurs="0"/>
 *         &lt;element name="communication-types" type="{urn:oma:xml:xdm:user-profile}communication-typesType" minOccurs="0"/>
 *         &lt;element name="hobbies" type="{urn:oma:xml:xdm:user-profile}hobbiesType" minOccurs="0"/>
 *         &lt;element name="favourite-links" type="{urn:oma:xml:xdm:user-profile}favourite-linksType" minOccurs="0"/>
 *         &lt;element name="maxAllowedActiveCommunications" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="maxActiveInstances" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user-profileType", namespace = "urn:oma:xml:xdm:user-profile", propOrder = {
    "communicationAddresses",
    "displayName",
    "birthDate",
    "name",
    "address",
    "gender",
    "freetext",
    "communicationTypes",
    "hobbies",
    "favouriteLinks",
    "maxAllowedActiveCommunications",
    "maxActiveInstances",
    "any"
})
public class UserProfileType {

    @XmlElement(name = "communication-addresses", namespace = "urn:oma:xml:xdm:user-profile")
    protected CommunicationAddressesType communicationAddresses;
    @XmlElement(name = "display-name", namespace = "urn:oma:xml:xdm:user-profile")
    protected DisplayNameType displayName;
    @XmlElement(name = "birth-date", namespace = "urn:oma:xml:xdm:user-profile")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected NameType name;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected AddressType address;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    @XmlSchemaType(name = "token")
    protected GenderType gender;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected FreetextType freetext;
    @XmlElement(name = "communication-types", namespace = "urn:oma:xml:xdm:user-profile")
    protected CommunicationTypesType communicationTypes;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected HobbiesType hobbies;
    @XmlElement(name = "favourite-links", namespace = "urn:oma:xml:xdm:user-profile")
    protected FavouriteLinksType favouriteLinks;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected Integer maxAllowedActiveCommunications;
    @XmlElement(namespace = "urn:oma:xml:xdm:user-profile")
    protected Integer maxActiveInstances;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "uri", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the communicationAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationAddressesType }
     *     
     */
    public CommunicationAddressesType getCommunicationAddresses() {
        return communicationAddresses;
    }

    /**
     * Sets the value of the communicationAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationAddressesType }
     *     
     */
    public void setCommunicationAddresses(CommunicationAddressesType value) {
        this.communicationAddresses = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayNameType }
     *     
     */
    public DisplayNameType getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayNameType }
     *     
     */
    public void setDisplayName(DisplayNameType value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setName(NameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderType }
     *     
     */
    public GenderType getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderType }
     *     
     */
    public void setGender(GenderType value) {
        this.gender = value;
    }

    /**
     * Gets the value of the freetext property.
     * 
     * @return
     *     possible object is
     *     {@link FreetextType }
     *     
     */
    public FreetextType getFreetext() {
        return freetext;
    }

    /**
     * Sets the value of the freetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreetextType }
     *     
     */
    public void setFreetext(FreetextType value) {
        this.freetext = value;
    }

    /**
     * Gets the value of the communicationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationTypesType }
     *     
     */
    public CommunicationTypesType getCommunicationTypes() {
        return communicationTypes;
    }

    /**
     * Sets the value of the communicationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationTypesType }
     *     
     */
    public void setCommunicationTypes(CommunicationTypesType value) {
        this.communicationTypes = value;
    }

    /**
     * Gets the value of the hobbies property.
     * 
     * @return
     *     possible object is
     *     {@link HobbiesType }
     *     
     */
    public HobbiesType getHobbies() {
        return hobbies;
    }

    /**
     * Sets the value of the hobbies property.
     * 
     * @param value
     *     allowed object is
     *     {@link HobbiesType }
     *     
     */
    public void setHobbies(HobbiesType value) {
        this.hobbies = value;
    }

    /**
     * Gets the value of the favouriteLinks property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteLinksType }
     *     
     */
    public FavouriteLinksType getFavouriteLinks() {
        return favouriteLinks;
    }

    /**
     * Sets the value of the favouriteLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteLinksType }
     *     
     */
    public void setFavouriteLinks(FavouriteLinksType value) {
        this.favouriteLinks = value;
    }

    /**
     * Gets the value of the maxAllowedActiveCommunications property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxAllowedActiveCommunications() {
        return maxAllowedActiveCommunications;
    }

    /**
     * Sets the value of the maxAllowedActiveCommunications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxAllowedActiveCommunications(Integer value) {
        this.maxAllowedActiveCommunications = value;
    }

    /**
     * Gets the value of the maxActiveInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxActiveInstances() {
        return maxActiveInstances;
    }

    /**
     * Sets the value of the maxActiveInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxActiveInstances(Integer value) {
        this.maxActiveInstances = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
